# Generated by Django 6.0.1 on 2026-04-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('profile', models.CharField(blank=True, max_length=64)),
                ('git_revision', models.CharField(blank=True, max_length=64)),
                ('started_at_utc', models.DateTimeField(blank=True, null=True)),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True)),
                ('manifest_path', models.CharField(blank=True, max_length=500)),
                ('publish_root', models.CharField(blank=True, max_length=500)),
                ('manifest_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-imported_at', 'run_id'],
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon_id', models.PositiveBigIntegerField(unique=True)),
                ('taxon_name', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('parent_taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='browser.taxon')),
            ],
            options={
                'ordering': ['taxon_name', 'taxon_id'],
            },
        ),
        migrations.CreateModel(
            name='TaxonClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_descendants', to='browser.taxon')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_ancestors', to='browser.taxon')),
            ],
            options={
                'ordering': ['ancestor__taxon_name', 'depth', 'descendant__taxon_name'],
            },
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['rank', 'taxon_name'], name='browser_taxon_rank_name_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonclosure',
            index=models.Index(fields=['ancestor', 'depth', 'descendant'], name='browser_taxon_closure_anc_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonclosure',
            index=models.Index(fields=['descendant', 'depth', 'ancestor'], name='browser_taxon_closure_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='browser_taxon_closure_unique_ancestor_descendant'),
        ),
        migrations.AddConstraint(
            model_name='taxonclosure',
            constraint=models.CheckConstraint(condition=models.Q(('depth__gte', 0)), name='browser_taxon_closure_depth_gte_zero'),
        ),
    ]
