# Generated by Django 6.0.1 on 2026-04-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genome_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=64)),
                ('accession', models.CharField(db_index=True, max_length=255)),
                ('genome_name', models.CharField(db_index=True, max_length=255)),
                ('assembly_type', models.CharField(max_length=128)),
                ('assembly_level', models.CharField(blank=True, max_length=128)),
                ('species_name', models.CharField(blank=True, max_length=255)),
                ('download_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='browser.pipelinerun')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genomes', to='browser.taxon')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'accession', 'genome_id'],
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protein_id', models.CharField(max_length=255)),
                ('protein_name', models.CharField(db_index=True, max_length=255)),
                ('protein_length', models.PositiveIntegerField()),
                ('protein_path', models.CharField(max_length=500)),
                ('gene_symbol', models.CharField(blank=True, db_index=True, max_length=255)),
                ('translation_method', models.CharField(blank=True, max_length=64)),
                ('translation_status', models.CharField(blank=True, max_length=64)),
                ('assembly_accession', models.CharField(blank=True, max_length=255)),
                ('gene_group', models.CharField(blank=True, max_length=255)),
                ('protein_external_id', models.CharField(blank=True, max_length=255)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='browser.genome')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='browser.pipelinerun')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proteins', to='browser.taxon')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'protein_name', 'protein_id'],
            },
        ),
        migrations.CreateModel(
            name='RunParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold')], db_index=True, max_length=20)),
                ('param_name', models.CharField(max_length=255)),
                ('param_value', models.CharField(max_length=255)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_parameters', to='browser.pipelinerun')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'method', 'param_name'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_id', models.CharField(max_length=255)),
                ('sequence_name', models.CharField(db_index=True, max_length=255)),
                ('sequence_length', models.PositiveIntegerField()),
                ('sequence_path', models.CharField(max_length=500)),
                ('gene_symbol', models.CharField(blank=True, db_index=True, max_length=255)),
                ('transcript_id', models.CharField(blank=True, max_length=255)),
                ('isoform_id', models.CharField(blank=True, max_length=255)),
                ('assembly_accession', models.CharField(blank=True, max_length=255)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('protein_external_id', models.CharField(blank=True, max_length=255)),
                ('translation_table', models.CharField(blank=True, max_length=32)),
                ('gene_group', models.CharField(blank=True, max_length=255)),
                ('linkage_status', models.CharField(blank=True, max_length=64)),
                ('partial_status', models.CharField(blank=True, max_length=64)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='browser.genome')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='browser.pipelinerun')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='browser.taxon')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'sequence_name', 'sequence_id'],
            },
        ),
        migrations.CreateModel(
            name='RepeatCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_id', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold')], db_index=True, max_length=20)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('repeat_residue', models.CharField(db_index=True, max_length=16)),
                ('repeat_count', models.PositiveIntegerField()),
                ('non_repeat_count', models.PositiveIntegerField()),
                ('purity', models.FloatField()),
                ('aa_sequence', models.TextField()),
                ('codon_sequence', models.TextField(blank=True)),
                ('codon_metric_name', models.CharField(blank=True, max_length=255)),
                ('codon_metric_value', models.CharField(blank=True, max_length=255)),
                ('window_definition', models.CharField(blank=True, max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('merge_rule', models.CharField(blank=True, max_length=255)),
                ('score', models.CharField(blank=True, max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.genome')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.pipelinerun')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.protein')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repeat_calls', to='browser.taxon')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.sequence')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'protein__protein_name', 'start', 'call_id'],
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='browser.sequence'),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['pipeline_run', 'accession'], name='brw_genome_run_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['pipeline_run', 'genome_name'], name='brw_genome_run_name_idx'),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['pipeline_run', 'taxon'], name='brw_genome_run_tax_idx'),
        ),
        migrations.AddConstraint(
            model_name='genome',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'genome_id'), name='browser_genome_unique_run_genome_id'),
        ),
        migrations.AddConstraint(
            model_name='runparameter',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'method', 'param_name'), name='browser_runparam_unique_run_method_name'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['pipeline_run', 'genome'], name='brw_seq_run_genome_idx'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['pipeline_run', 'taxon'], name='brw_seq_run_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['pipeline_run', 'gene_symbol'], name='brw_seq_run_gene_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'sequence_id'), name='browser_sequence_unique_run_sequence_id'),
        ),
        migrations.AddIndex(
            model_name='repeatcall',
            index=models.Index(fields=['pipeline_run', 'method'], name='brw_rcall_run_method_idx'),
        ),
        migrations.AddIndex(
            model_name='repeatcall',
            index=models.Index(fields=['pipeline_run', 'repeat_residue'], name='brw_rcall_run_residue_idx'),
        ),
        migrations.AddIndex(
            model_name='repeatcall',
            index=models.Index(fields=['pipeline_run', 'taxon'], name='brw_rcall_run_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='repeatcall',
            index=models.Index(fields=['pipeline_run', 'protein'], name='brw_rcall_run_protein_idx'),
        ),
        migrations.AddIndex(
            model_name='repeatcall',
            index=models.Index(fields=['pipeline_run', 'length'], name='brw_rcall_run_length_idx'),
        ),
        migrations.AddConstraint(
            model_name='repeatcall',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'call_id'), name='browser_repeatcall_unique_run_call_id'),
        ),
        migrations.AddConstraint(
            model_name='repeatcall',
            constraint=models.CheckConstraint(condition=models.Q(('purity__gte', 0), ('purity__lte', 1)), name='browser_repeatcall_purity_between_zero_one'),
        ),
        migrations.AddConstraint(
            model_name='repeatcall',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='browser_repeatcall_end_gte_start'),
        ),
        migrations.AddIndex(
            model_name='protein',
            index=models.Index(fields=['pipeline_run', 'genome'], name='brw_protein_run_genome_idx'),
        ),
        migrations.AddIndex(
            model_name='protein',
            index=models.Index(fields=['pipeline_run', 'taxon'], name='brw_protein_run_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='protein',
            index=models.Index(fields=['pipeline_run', 'gene_symbol'], name='brw_protein_run_gene_idx'),
        ),
        migrations.AddConstraint(
            model_name='protein',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'protein_id'), name='browser_protein_unique_run_protein_id'),
        ),
    ]
