# Generated by Django 6.0.1 on 2026-04-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0002_genome_protein_runparameter_sequence_repeatcall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genome",
            name="analyzed_protein_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
