# Generated by Django 6.0.1 on 2026-04-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_genome_analyzed_protein_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runparameter',
            options={'ordering': ['pipeline_run__run_id', 'method', 'repeat_residue', 'param_name']},
        ),
        migrations.RemoveConstraint(
            model_name='runparameter',
            name='browser_runparam_unique_run_method_name',
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='acquisition_publish_mode',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='runparameter',
            name='repeat_residue',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='repeatcall',
            name='method',
            field=models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold'), ('seed_extend', 'Seed Extend')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='method',
            field=models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold'), ('seed_extend', 'Seed Extend')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='runparameter',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'method', 'repeat_residue', 'param_name'), name='browser_runparam_unique_run_method_residue_name'),
        ),
    ]
