# Generated by Django 6.0.1 on 2026-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_alter_runparameter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='amino_acid_sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='nucleotide_sequence',
            field=models.TextField(blank=True),
        ),
    ]
