# Generated by Django 6.0.1 on 2026-04-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_protein_amino_acid_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=255)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_batches', to='browser.pipelinerun')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'batch_id'],
            },
        ),
        migrations.AddField(
            model_name='genome',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genomes', to='browser.acquisitionbatch'),
        ),
        migrations.AddConstraint(
            model_name='acquisitionbatch',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'batch_id'), name='browser_acqbatch_unique_run_batch_id'),
        ),
    ]
