# Generated by Django 6.0.1 on 2026-04-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_acquisitionbatch_genome_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionCallCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_accession', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold'), ('seed_extend', 'Seed Extend')], db_index=True, max_length=20)),
                ('repeat_residue', models.CharField(blank=True, db_index=True, max_length=16)),
                ('detect_status', models.CharField(blank=True, max_length=64)),
                ('finalize_status', models.CharField(blank=True, max_length=64)),
                ('n_repeat_calls', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accession_call_count_rows', to='browser.acquisitionbatch')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accession_call_count_rows', to='browser.pipelinerun')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'assembly_accession', 'method', 'repeat_residue'],
                'indexes': [models.Index(fields=['pipeline_run', 'method', 'repeat_residue'], name='brw_acccall_run_method_res_idx')],
                'constraints': [models.UniqueConstraint(fields=('pipeline_run', 'assembly_accession', 'method', 'repeat_residue'), name='browser_acccallcount_unique_run_accession_method_residue')],
            },
        ),
        migrations.CreateModel(
            name='AccessionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_accession', models.CharField(db_index=True, max_length=255)),
                ('download_status', models.CharField(blank=True, max_length=64)),
                ('normalize_status', models.CharField(blank=True, max_length=64)),
                ('translate_status', models.CharField(blank=True, max_length=64)),
                ('detect_status', models.CharField(blank=True, max_length=64)),
                ('finalize_status', models.CharField(blank=True, max_length=64)),
                ('terminal_status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('failure_stage', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('n_genomes', models.PositiveIntegerField(default=0)),
                ('n_proteins', models.PositiveIntegerField(default=0)),
                ('n_repeat_calls', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accession_status_rows', to='browser.acquisitionbatch')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accession_status_rows', to='browser.pipelinerun')),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'assembly_accession'],
                'indexes': [models.Index(fields=['pipeline_run', 'terminal_status'], name='brw_accstatus_run_terminal_idx')],
                'constraints': [models.UniqueConstraint(fields=('pipeline_run', 'assembly_accession'), name='browser_accstatus_unique_run_accession')],
            },
        ),
    ]
