# Generated by Django 6.0.1 on 2026-04-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_accessioncallcount_accessionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='download_path',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='protein_path',
        ),
        migrations.RemoveField(
            model_name='repeatcall',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='sequence_path',
        ),
    ]
