# Generated by Django 6.0.1 on 2026-04-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_remove_genome_download_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadManifestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_accession', models.CharField(db_index=True, max_length=255)),
                ('download_status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('package_mode', models.CharField(blank=True, max_length=64)),
                ('download_path', models.CharField(blank=True, max_length=500)),
                ('rehydrated_path', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('download_started_at', models.DateTimeField(blank=True, null=True)),
                ('download_finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'batch__batch_id', 'assembly_accession'],
            },
        ),
        migrations.CreateModel(
            name='NormalizationWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warning_code', models.CharField(db_index=True, max_length=255)),
                ('warning_scope', models.CharField(blank=True, db_index=True, max_length=64)),
                ('warning_message', models.TextField(blank=True)),
                ('genome_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sequence_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('protein_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('assembly_accession', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['pipeline_run__run_id', 'batch__batch_id', 'warning_code', 'assembly_accession'],
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='accession',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='protein',
            name='repeat_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repeatcall',
            name='accession',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repeatcall',
            name='gene_symbol',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repeatcall',
            name='protein_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repeatcall',
            name='protein_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='protein',
            index=models.Index(fields=['pipeline_run', 'accession'], name='brw_protein_run_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='repeatcall',
            index=models.Index(fields=['pipeline_run', 'accession'], name='brw_rcall_run_acc_idx'),
        ),
        migrations.AddField(
            model_name='downloadmanifestentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_manifest_entries', to='browser.acquisitionbatch'),
        ),
        migrations.AddField(
            model_name='downloadmanifestentry',
            name='pipeline_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_manifest_entries', to='browser.pipelinerun'),
        ),
        migrations.AddField(
            model_name='normalizationwarning',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalization_warnings', to='browser.acquisitionbatch'),
        ),
        migrations.AddField(
            model_name='normalizationwarning',
            name='pipeline_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_warnings', to='browser.pipelinerun'),
        ),
        migrations.AddIndex(
            model_name='downloadmanifestentry',
            index=models.Index(fields=['pipeline_run', 'batch'], name='brw_dlmfest_run_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadmanifestentry',
            index=models.Index(fields=['pipeline_run', 'download_status'], name='brw_dlmfest_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadmanifestentry',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'batch', 'assembly_accession'), name='browser_dlmfest_unique_run_batch_accession'),
        ),
        migrations.AddIndex(
            model_name='normalizationwarning',
            index=models.Index(fields=['pipeline_run', 'batch'], name='brw_normwarn_run_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizationwarning',
            index=models.Index(fields=['pipeline_run', 'assembly_accession'], name='brw_normwarn_run_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizationwarning',
            index=models.Index(fields=['pipeline_run', 'warning_code', 'warning_scope'], name='brw_normwarn_run_code_idx'),
        ),
    ]
