# Generated by Django 6.0.1 on 2026-04-12 00:00

from django.db import migrations, models


def _browser_metadata_field():
    field = models.JSONField(blank=True, default=dict)
    field.set_attributes_from_name("browser_metadata")
    return field


def add_browser_metadata_if_missing(apps, schema_editor):
    PipelineRun = apps.get_model("browser", "PipelineRun")
    table_name = PipelineRun._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if "browser_metadata" in columns:
        return
    schema_editor.add_field(PipelineRun, _browser_metadata_field())


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0009_downloadmanifestentry_normalizationwarning_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_browser_metadata_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="pipelinerun",
                    name="browser_metadata",
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
