# Generated by Django 6.0.1 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0010_pipelinerun_browser_metadata"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sequence",
            index=models.Index(
                fields=["pipeline_run", "assembly_accession", "sequence_name", "id"],
                name="brw_seq_run_asm_name_id",
            ),
        ),
        migrations.AddIndex(
            model_name="protein",
            index=models.Index(
                fields=["pipeline_run", "accession", "protein_name", "id"],
                name="brw_prot_run_acc_name_id",
            ),
        ),
        migrations.AddIndex(
            model_name="repeatcall",
            index=models.Index(
                fields=["pipeline_run", "accession", "protein_name", "start", "id"],
                name="brw_rc_run_acc_pn_start_id",
            ),
        ),
    ]
