# Generated by Django 6.0.1 on 2026-04-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_mergedproteinsummary_mergedproteinoccurrence_and_more'),
        ('imports', '0003_importbatch_heartbeat_at_importbatch_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('genome_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=64)),
                ('accession', models.CharField(db_index=True, max_length=255, unique=True)),
                ('genome_name', models.CharField(db_index=True, max_length=255)),
                ('assembly_type', models.CharField(max_length=128)),
                ('assembly_level', models.CharField(blank=True, max_length=128)),
                ('species_name', models.CharField(blank=True, max_length=255)),
                ('analyzed_protein_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('latest_import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_genomes', to='imports.importbatch')),
                ('latest_pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_genomes', to='browser.pipelinerun')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_genomes', to='browser.taxon')),
            ],
            options={
                'ordering': ['accession'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('protein_id', models.CharField(max_length=255)),
                ('protein_name', models.CharField(db_index=True, max_length=255)),
                ('protein_length', models.PositiveIntegerField()),
                ('accession', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amino_acid_sequence', models.TextField(blank=True)),
                ('gene_symbol', models.CharField(blank=True, db_index=True, max_length=255)),
                ('translation_method', models.CharField(blank=True, max_length=64)),
                ('translation_status', models.CharField(blank=True, max_length=64)),
                ('assembly_accession', models.CharField(blank=True, max_length=255)),
                ('gene_group', models.CharField(blank=True, max_length=255)),
                ('protein_external_id', models.CharField(blank=True, max_length=255)),
                ('repeat_call_count', models.PositiveIntegerField(default=0)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='browser.canonicalgenome')),
                ('latest_import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_proteins', to='imports.importbatch')),
                ('latest_pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_proteins', to='browser.pipelinerun')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_proteins', to='browser.taxon')),
            ],
            options={
                'ordering': ['genome__accession', 'protein_name', 'protein_id'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('sequence_id', models.CharField(max_length=255)),
                ('sequence_name', models.CharField(db_index=True, max_length=255)),
                ('sequence_length', models.PositiveIntegerField()),
                ('nucleotide_sequence', models.TextField(blank=True)),
                ('gene_symbol', models.CharField(blank=True, db_index=True, max_length=255)),
                ('transcript_id', models.CharField(blank=True, max_length=255)),
                ('isoform_id', models.CharField(blank=True, max_length=255)),
                ('assembly_accession', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('protein_external_id', models.CharField(blank=True, max_length=255)),
                ('translation_table', models.CharField(blank=True, max_length=32)),
                ('gene_group', models.CharField(blank=True, max_length=255)),
                ('linkage_status', models.CharField(blank=True, max_length=64)),
                ('partial_status', models.CharField(blank=True, max_length=64)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='browser.canonicalgenome')),
                ('latest_import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_sequences', to='imports.importbatch')),
                ('latest_pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_sequences', to='browser.pipelinerun')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_sequences', to='browser.taxon')),
            ],
            options={
                'ordering': ['genome__accession', 'sequence_name', 'sequence_id'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalRepeatCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('source_call_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('pure', 'Pure'), ('threshold', 'Threshold'), ('seed_extend', 'Seed Extend')], db_index=True, max_length=20)),
                ('accession', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gene_symbol', models.CharField(blank=True, db_index=True, max_length=255)),
                ('protein_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('protein_length', models.PositiveIntegerField(default=0)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('repeat_residue', models.CharField(db_index=True, max_length=16)),
                ('repeat_count', models.PositiveIntegerField()),
                ('non_repeat_count', models.PositiveIntegerField()),
                ('purity', models.FloatField()),
                ('aa_sequence', models.TextField()),
                ('codon_sequence', models.TextField(blank=True)),
                ('codon_metric_name', models.CharField(blank=True, max_length=255)),
                ('codon_metric_value', models.CharField(blank=True, max_length=255)),
                ('window_definition', models.CharField(blank=True, max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('merge_rule', models.CharField(blank=True, max_length=255)),
                ('score', models.CharField(blank=True, max_length=255)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.canonicalgenome')),
                ('latest_import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_repeat_calls', to='imports.importbatch')),
                ('latest_pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_repeat_calls', to='browser.pipelinerun')),
                ('latest_repeat_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='browser.repeatcall')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.canonicalprotein')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_repeat_calls', to='browser.taxon')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_calls', to='browser.canonicalsequence')),
            ],
            options={
                'ordering': ['accession', 'protein_name', 'start', 'id'],
            },
        ),
        migrations.AddField(
            model_name='canonicalprotein',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='browser.canonicalsequence'),
        ),
        migrations.AddIndex(
            model_name='canonicalgenome',
            index=models.Index(fields=['genome_name'], name='brw_cgenome_name_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalgenome',
            index=models.Index(fields=['taxon'], name='brw_cgenome_tax_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalsequence',
            index=models.Index(fields=['assembly_accession', 'sequence_name', 'id'], name='brw_cseq_acc_name_id'),
        ),
        migrations.AddIndex(
            model_name='canonicalsequence',
            index=models.Index(fields=['genome'], name='brw_cseq_genome_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalsequence',
            index=models.Index(fields=['taxon'], name='brw_cseq_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalsequence',
            index=models.Index(fields=['gene_symbol'], name='brw_cseq_gene_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalsequence',
            constraint=models.UniqueConstraint(fields=('genome', 'sequence_id'), name='brw_cseq_unique_genome_sid'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['accession', 'protein_name', 'start', 'id'], name='brw_crcall_acc_name_sid'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['method'], name='brw_crcall_method_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['repeat_residue'], name='brw_crcall_res_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['taxon'], name='brw_crcall_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['protein'], name='brw_crcall_protein_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['length'], name='brw_crcall_length_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['method', 'repeat_residue', 'accession', 'id'], name='brw_crcall_mra_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalrepeatcall',
            constraint=models.UniqueConstraint(fields=('protein', 'sequence', 'method', 'repeat_residue', 'start', 'end'), name='brw_crcall_unique_scope'),
        ),
        migrations.AddConstraint(
            model_name='canonicalrepeatcall',
            constraint=models.CheckConstraint(condition=models.Q(('purity__gte', 0), ('purity__lte', 1)), name='brw_crcall_purity_0_1'),
        ),
        migrations.AddConstraint(
            model_name='canonicalrepeatcall',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='brw_crcall_end_gte_start'),
        ),
        migrations.AddIndex(
            model_name='canonicalprotein',
            index=models.Index(fields=['accession', 'protein_name', 'id'], name='brw_cprot_acc_name_id'),
        ),
        migrations.AddIndex(
            model_name='canonicalprotein',
            index=models.Index(fields=['genome'], name='brw_cprot_genome_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalprotein',
            index=models.Index(fields=['taxon'], name='brw_cprot_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalprotein',
            index=models.Index(fields=['gene_symbol'], name='brw_cprot_gene_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalprotein',
            constraint=models.UniqueConstraint(fields=('genome', 'protein_id'), name='brw_cprot_unique_genome_pid'),
        ),
    ]
