# Generated by Django 6.0.1 on 2026-04-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0013_canonicalgenome_canonicalprotein_canonicalsequence_and_more'),
        ('imports', '0003_importbatch_heartbeat_at_importbatch_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='canonical_sync_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_synced_runs', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='canonical_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
