# Generated by Django 5.2.8 on 2026-04-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0016_delete_merged_schema'),
        ('imports', '0003_importbatch_heartbeat_at_importbatch_phase_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='canonicalprotein',
            index=models.Index(fields=['protein_id'], name='brw_cprot_pid_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrepeatcall',
            index=models.Index(fields=['latest_pipeline_run', 'taxon', 'length'], name='brw_crcall_run_tax_len_idx'),
        ),
    ]
