# Generated by Django 5.2.8 on 2026-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browser", "0017_canonicalprotein_brw_cprot_pid_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalrepeatcall",
            name="codon_ratio_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repeatcall",
            name="codon_ratio_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
