# Generated by Django 6.0.1 on 2026-04-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_repeatcall_codon_ratio_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalRepeatCallCodonUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amino_acid', models.CharField(db_index=True, max_length=16)),
                ('codon', models.CharField(db_index=True, max_length=16)),
                ('codon_count', models.PositiveIntegerField()),
                ('codon_fraction', models.FloatField()),
                ('repeat_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codon_usages', to='browser.canonicalrepeatcall')),
            ],
            options={
                'ordering': ['repeat_call_id', 'amino_acid', 'codon'],
                'indexes': [models.Index(fields=['amino_acid', 'codon'], name='brw_crccu_aa_codon_idx')],
                'constraints': [models.UniqueConstraint(fields=('repeat_call', 'amino_acid', 'codon'), name='brw_crccu_unique_call_aa_codon'), models.CheckConstraint(condition=models.Q(('codon_fraction__gte', 0), ('codon_fraction__lte', 1)), name='brw_crccu_fraction_0_1')],
            },
        ),
        migrations.CreateModel(
            name='RepeatCallCodonUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amino_acid', models.CharField(db_index=True, max_length=16)),
                ('codon', models.CharField(db_index=True, max_length=16)),
                ('codon_count', models.PositiveIntegerField()),
                ('codon_fraction', models.FloatField()),
                ('repeat_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codon_usages', to='browser.repeatcall')),
            ],
            options={
                'verbose_name': 'imported repeat-call codon-usage row',
                'verbose_name_plural': 'imported repeat-call codon-usage rows',
                'ordering': ['repeat_call_id', 'amino_acid', 'codon'],
                'indexes': [models.Index(fields=['amino_acid', 'codon'], name='brw_rccu_aa_codon_idx')],
                'constraints': [models.UniqueConstraint(fields=('repeat_call', 'amino_acid', 'codon'), name='brw_rccu_unique_call_aa_codon'), models.CheckConstraint(condition=models.Q(('codon_fraction__gte', 0), ('codon_fraction__lte', 1)), name='brw_rccu_fraction_0_1')],
            },
        ),
    ]
