# Generated by Django 6.0.1 on 2026-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0025_repeat_call_context'),
        ('imports', '0009_uploadedrun_actor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='delete_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='deleting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('delete_failed', 'Delete Failed')], default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='canonicalgenome',
            index=models.Index(fields=['latest_pipeline_run'], name='brw_cgenome_run_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalprotein',
            index=models.Index(fields=['latest_pipeline_run'], name='brw_cprot_run_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalsequence',
            index=models.Index(fields=['latest_pipeline_run'], name='brw_cseq_run_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['lifecycle_status', 'imported_at', 'id'], name='brw_run_lifecycle_imported_idx'),
        ),
    ]
