# Generated by Django 6.0.1 on 2026-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="row_counts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
