# Generated by Django 6.0.1 on 2026-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importbatch_row_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='phase',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='progress_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
