# Generated by Django 6.0.1 on 2026-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0003_importbatch_heartbeat_at_importbatch_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
