# Generated by Django 6.0.1 on 2026-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_importbatch_celery_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)),
                        name="imports_catalog_version_singleton",
                    )
                ],
            },
        ),
    ]
