# Generated by Django 6.0.1 on 2026-05-02 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0026_pipelinerun_lifecycle_and_canonical_run_indexes'),
        ('imports', '0009_uploadedrun_actor_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('pipeline_run', 'Pipeline Run')], default='pipeline_run', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('phase', models.CharField(blank=True, max_length=64)),
                ('requested_by_label', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_debug', models.JSONField(blank=True, default=dict)),
                ('rows_planned', models.PositiveIntegerField(default=0)),
                ('rows_deleted', models.PositiveIntegerField(default=0)),
                ('artifacts_planned', models.PositiveIntegerField(default=0)),
                ('artifacts_deleted', models.PositiveIntegerField(default=0)),
                ('catalog_versions', models.JSONField(blank=True, default=list)),
                ('current_table', models.CharField(blank=True, max_length=128)),
                ('current_chunk_size', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_jobs', to='browser.pipelinerun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pipeline_run', 'status'], name='imports_djob_run_status_idx')],
            },
        ),
    ]
