# Generated by Django 6.0.1 on 2026-05-02 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0026_pipelinerun_lifecycle_and_canonical_run_indexes'),
        ('imports', '0010_deletionjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deletionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('pipeline_run',), name='imports_djob_unique_active_per_run'),
        ),
    ]
